apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name.app.name}}
  labels:
    app: {{.Values.name.app.name}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name.app.name}}
    spec:
      containers:
        - name: {{.Values.name.app.name}}
          image: {{.Values.name.app.image}}
          args:
            - "busybox"
            - "httpd"
            - "-f"
            - "-p"
            - "8080"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name.app.name}}
spec:
  selector:
    app: {{.Values.name.app.name}}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.ports.external }}
